version: "3.6"

services:
  web:
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    volumes:
      - .:/opt/app
    ports:
      - "8000:3000"
    links:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: "chat"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "12345678"
      MYSQL_ROOT_PASSWORD: "12345678"
    ports:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:
